var map = {
    'MSC': [
        'Saheshna Karar',
        'Shreya Basak',
        'Rishita Sengupta',
        'Debarati Barman',
        'Ahona Bose',
        'Doyel Swarnakar',
        'Sanjana Poddar',
        'Diotima Nag',
        'Nabanita Saha',
        'Sanchari Rana',
        'Sharavani Mondal',
        'Kakan Basak',
        'Shimul Bhattacharjee',
        'Sriparna Banerjee',
        'Tiyasa De',
        'Sreeparna Roy',
        'Somrita Ghosh',
        'Sayantan Saha',
        'Sumit Kumar',
        'Subhadeep Das',
        'Krishna Nandan Mondal',
        'Akash Saha',
        'Kiran Naskar',
    ],
    'MTECH': [
        'Debtirtha Biswas', 
        'Devanjana Chatterjee', 
        'Bidisha Barua', 
        'Sanchari Banerjee', 
        'Debolina Chowdhury', 
        'Kanyaka Chakraborty', 
        'Paulamy Majee', 
        'Sreeja Ray', 
        'Saptaparna Kundu', 
        'Abhimanyu Chatterjee', 
        'Sumanjit Kuity', 
        'Ankit Shaw', 
        'Shatanik Chakraborty', 
        'Tirthankar Ghosh', 
        'Rahul Dutta', 
        'Rajarshi Bhattacharya', 
        'Kaustav Bhattacharjee', 
        'Rounak Saha'
    ],
    'BTECH': [
        'Trisha Halder', 
        'Sayak Halder', 
        'Sauradeep Sikdar', 
        'Chittadip Bag', 
        'Akashdeep Pandey', 
        'Prateek Ganguli', 
        'Sushant Lama', 
        'Abhishek Raj', 
        'Md Shalique', 
        'Soukarsha Moulik', 
        'Bikram Dey', 
    ]
};
